version: '3.1'
services:

  postgres:
    image: postgres:9.5-alpine
    container_name: app-postgres
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app-php-fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app-php-fpm
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  webserver:
    image: nginx:alpine
    container_name: app-webserver
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
